SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME 
FROM ANIMAL_INS I LEFT JOIN ANIMAL_OUTS O ON I.ANIMAL_ID=O.ANIMAL_ID
WHERE SEX_UPON_INTAKE like 'Intact%' and (SEX_UPON_OUTCOME like 'Neu%' or SEX_UPON_OUTCOME like 'Spayed%')
ORDER BY I.ANIMAL_ID ASC
