SELECT T.NAME, T.DATETIME FROM
(SELECT I.NAME, I.DATETIME, RANK() OVER (ORDER BY I.DATETIME ASC) RANK
FROM ANIMAL_INS I LEFT OUTER JOIN ANIMAL_OUTS O ON I.ANIMAL_ID=O.ANIMAL_ID
WHERE O.DATETIME IS NULL AND ROWNUM<=3)  T;
